config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  get 'profiles/show'
  get 'profiles/update'
  devise_for :users

  mount Sidekiq::Web => '/sidekiq'
  # get 'home/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  # get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  root 'home#index'

  resource :profile

  resources :movies do
    collection do
      get :omdb_search
      post :omdb_import
    end

    resources :comments

  

  # resources :movies do
  #   resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :commentable, polymorphic: true
  belongs_to :user

  has_many :comments, as: :commentable, dependent: :destroy

  validates :body, presence: true, length: { minimum: 10, maximum: 500 }

  after_create :send_email

  private

  def send_email
    CommentMailer.with(user: user, comment: self).created.deliver_later
  end

end

app/models/movie.rb
class Movie < ApplicationRecord
    GENRES = %W[action comedy drama horror romance thriller fantasy animation documentary musical western].freeze

    has_many :comments, as: :commentable, dependent: :destroy

    validates :title, :year_of_creation, :duration, :director, presence: true
    validates :title, uniqueness: { scope: %i[year_of_creation] }
    validates :description, length: { minimum: 15 }
    validate :genres_validation

    private

    def genres_validation
        # genres.is_a?(Array) && genres.any? { |g| g.present? }
        unless genres.is_a?(Array) && genres.any?(&:present?)
            errors.add(:genres, 'at least one genre must be selected')
        end
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :comments, dependent: :destroy

  has_one_attached :avatar do |attachable|
    attachable.variant :tiny, resize_to_limit: [50, 50]
  end

  def full_name
    return email if first_name.blank? && last_name.blank?
    
    "#{first_name} #{last_name}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include Pundit::Authorization
    
    protect_from_forgery prepend: true
    before_action :authenticate_user!
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
   before_action :find_movie
   before_action :find_and_authorize_comment, except: :create

    def create
        @comment = Comment.build(user: current_user, **comment_params)

        flash[:error] = @comment.errors.full_messages.join(", ") unless @comment.save

        redirect_to @movie
    end

    def edit
        # redirect_to edit_movie_comment_path(@comment)
    end

    def update
        @comment.assign_attributes(comment_params)
        if @comment.save
            redirect_to @comment.commentable
        else
            flash[:alert] = @comment.errors.full_messages.join(", ")
            render :edit
        end
    end

    def destroy
        @comment.destroy
    end

    def comment_params
        params.require(:comment).permit(:body, :commentable_id, :commentable_type)
    end

    def find_movie
        @movie = Movie.find(params[:movie_id])
    end

    def find_and_authorize_comment
        @comment = Comment.find(params[:id])
        authorize @comment
    end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
    #GET /movies
    def index
        @movies = Movie.all
    end

    #GET /movies/:id
    def show
        @movie = Movie.find(params[:id])
        @omdb = OmdbClient.new
        @omdb_movie = @omdb.search(@movie.title)
    end

    # GET /movies/new
    def new
        @movie = Movie.new
    end

    #POST /movies
    def create
        @movie = Movie.new(movie_params)
        if @movie.save
            redirect_to @movie
        else
            flash[:alert] = @movie.errors.full_messages.join(", ")
            redirect_to new_movie_path
        end
    end

    #GET /movies/:id/edit
    def edit
        @movie = Movie.find(params[:id])
    end

    #PUT/PATCH /movies/:id
    def update
        @movie = Movie.find(params[:id])
        @movie.assign_attributes(movie_params)
        if @movie.save
            redirect_to @movie
        else
            flash[:alert] = @movie.errors.full_messages.join(", ")
            redirect_to @movie
        end
    end
    
    #DELETE /movies/:id
    def destroy
        @movie = Movie.find(params[:id])
        movie.destroy
    end

    def movie_params
        params.require(:movie).permit(:title, :description, :duration, :director, :year_of_creation, genres: [])
    end

    def find_movie
        @movie = Movie.find(params[:id])
    end

    def omdb_search
        if params[:search_query].present?
            @omdb = OmdbClient.new
            res = @omdb.search(params[:search_query])
            @search_results = res['Search']
        end
    end

    def omdb_import
        # @omdb = OmdbClient.new

        # @omdb_movie = @omdb.find_by_id(params[:omdb_id])

        # @movie = Movie.new(
        #     title: @omdb_movie['Title'],
        #     cover_image_url: @omdb_movie['Poster'],
        #     year_of_creation: @omdb_movie['Year'],
        #     description: @omdb_movie['Plot'],
        #     duration: @omdb_movie['Runtime'],
        #     director: @omdb_movie['Director'],
        #     genres: @omdb_movie['Genre'].split(', ')
        # )

        
        # if @movie.save
        #     redirect_to @movie
        # else
        #     flash[:alert] = @movie.errors.full_messages.join(", ")
        #     redirect_to omdb_search_movies_path
        # end
        MoviesImportJob.perform_later(params[:omdb_id], current_user)
        flash[:notice] = 'Movie will be imported soon' 
        redirect_to movies_path
    end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def edit
  end

  def update  
    if current_user.update(profile_params)
      flash[:notice] = 'Profile updated'
      redirect_to root_path
    else
      flash[:alert] = current_user.errors.full_messages.join(", ")
    end
  end

  private

  def profile_params
    params.require(:user).permit(:first_name, :last_name, :avatar)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/comments/_form.html.erb
<% if comment_to.is_a?(Movie) %>
  <% movie = comment_to %>
  <h4>Create</h4>
<% elsif comment_to.is_a?(Comment) %>
  <% movie = comment_to.commentable %>
  <h5>Reply</h5>
<% end %>
<h1>Create comment</h1>
<%= form_for :comment, url: movie_comments_path(movie) do |form| %>
  <%= form.hidden_field :commentable_type, value: comment_to.class.name %>
  <%= form.hidden_field :commentable_id, value: comment_to.id %>
  <%= form.text_field :body %>
  <%= form.submit class: "btn" %>
<% end %>

app/views/comments/destroy.turbo_stream.erb
<%= turbo_stream.remove dom_id(@comment) %>
<%= flash[:notice] = 'Comment deleted' %>

app/views/comments/edit.html.erb
<h1>Edit Comment</h1>

<%= form_for @comment, url: movie_comment_path(@comment, movie_id: @comment.commentable.id), method: :patch do |form| %>
  <div class="field">
    <%= form.text_area :body, class: "form-control" %>
  </div>
  <div class="actions">
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/home/index.html.erb
<h1>Hello World!</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProjectName</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%# <%= stylesheet_link_tag "css/pico.min.css" %> 
  </head>

  <body>
    <%= turbo_include_tags %>
    <% if notice.present? || alert.present? %>
      <p class="notice"><%= notice %></p>
    <% end %>
    <% if alert.present? %>
      <p class="alert"><%= alert %></p>
    <% end %>
    <%= render 'shared/header' %>
    <div class="container"><%= yield %></div>
  </body>
</html>

app/views/movies/edit.html.erb
<h1>Edit Movie</h1>

<%= render 'movies/shared/form', movie: @movie %>

app/views/movies/index.html.erb
<h1>All Movies</h1>

<% @movies.each do |movie| %>
    <h2>Title: <%= (link_to movie.title, movie_path(movie)) %></h2>
    <h3>Description: <%= movie.description %></h3>
    <p>Year of creation: <%= movie.year_of_creation %></p>
    <p>Genre: <%= movie.genres %></p>
    <p>Director: <%= movie.director %></p>
<% end %>

app/views/movies/new.html.erb
<h1>New Project</h1>

<%= render 'movies/shared/form', movie: @movie %>

app/views/movies/omdb_search.html.erb
<h1>Omdb search</h1>
<%= form_tag omdb_search_movies_path, method: :get do %>
    <div style='margin-bottom: 10 px;'>
        <%= label_tag :search_query %>
        <%= text_field_tag :search_query, params[:search_query] %>
    </div>

    <%= submit_tag 'Search' %>
<% end %>

<% if @search_results.present? %>
  <table>
    <thead>
      <th>Title</th>
      <th>Year</th>
      <th>Image</th>
      <th>Actions</th>
    </thead>
    <tbody>
      <% @search_results.each do |movie| %>
        <tr>
          <td><%= movie['Title'] %></td>
          <td><%= movie['Year'] %></td>
          <td>
            <% if movie['Poster'] != 'N/A' %>
              <%= image_tag(movie['Poster']) %>
            <% else %>
              No Image Available
            <% end %>
          </td>
          <td>
            <%= form_tag omdb_import_movies_path(omdb_id: movie['imdbID']), method: :post do %>
              <%= submit_tag 'Import' %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/movies/shared/_form.html.erb
<%= form_for movie do |form| %>
    <div style = 'margin-bottom: 10px'>
    <%= form.label :title , style: 'display: block' %>
    <%= form.text_field :title %>
    </div>

    <div style = 'margin-bottom: 10px'>
    <%= form.label :description , style: 'display: block' %>
    <%= form.text_area :description %>
    </div>

    <div style = 'margin-bottom: 10px'>
    <%= form.label :duration , style: 'display: block' %>
    <%= form.text_field :duration %>
    </div>

    <div style = 'margin-bottom: 10px'>
    <%= form.label :director , style: 'display: block' %>
    <%= form.text_field :director %>
    </div>

    <div style = 'margin-bottom: 10px'>
    <%= form.label :year_of_creation , style: 'display: block' %>
    <%= form.number_field :year_of_creation %>
    </div>

    <div style = 'margin-bottom: 10px'>
    <%= form.label :genres , style: 'display: block' %>
    <%= form.select :genres, Movie::GENRES, multiple: true %>
    </div>

    <%= form.submit %>
<% end %>

app/views/movies/show.html.erb
<h1>Show View</h1>
<%= @movie.title%>
<h2>Title: <%= @movie.title %></h2>
<h3>Description: <%= @movie.description %></h3>
<p>Year of creation: <%= @movie.year_of_creation %></p>
<p>Genre: <%= @movie.genres %></p>
<p>Director: <%= @movie.director %></p>
<p><%= link_to 'Edit', edit_movie_path(@movie) %></p>

<hr/>
<article>
    <h3>OMDB info</h3>
    <p></p>
    <%= @omdb_movie['Title']%>
    <%= @omdb_movie['Year']%>
    <%= @omdb_movie['Rated'] %>
</article>

<% @movie.comments.includes(:user).each do |comment| %>
    <%= turbo_frame_tag(dom_id(comment)) do %>
        <p><%= comment.body %> (by <%= comment.user.email%>)</p>
        <% if policy(comment).edit? %>
            <%= link_to 'edit', edit_movie_comment_path(comment, movie_id: comment.commentable.id), "data-turbo": false %>
        <%end%>
        <% if policy(comment).destroy? %>
            <%= link_to('destroy', movie_comment_path(comment, movie_id: comment.commentable),
                data: {'turbo-method'=> :delete})%>
        <% end %>
        <% comment.comments.includes(:user).each do |sub_comment| %>
            <p><%= sub_comment.body %> (by <%= sub_comment.user.email%>)</p>
            <br/>
        <%end%>
        <div class ="container-small"><%= render partial: 'comments/form', locals: { comment_to: comment } %></div>
    <% end %>
<% end %>
<%= render partial: 'comments/form', locals: { comment_to: @movie } %>

app/views/profiles/edit.html.erb
<h1><%= current_user.full_name %>></h1>
<% if current_user.avatar.attached? %>
    <%= image_tag(current_user.avatar) %>\
<% end %>

<article>
    <%= form_for(current_user, url: profile_path(current_user), method: :put) do |f| %>
        <div>
            <%= f.label :first_name %>
            <%= f.text_field :first_name %>
        </div>
        <div>
            <%= f.label :last_name %>
            <%= f.text_field :last_name %>
        </div>
        <div>
            <%= f.file_field :avatar %>
        </div>
        <%= f.submit %>
    <% end %>
</article>

app/views/shared/_header.html.erb
<% if user_signed_in? %>
    <div class='pull_right'>
        <%= image_tag(current_user.avatar.variant(:tiny)) if current_user.avatar.attached? %>
        <%= link_to(current_user.full_name, edit_profile_path) %>
        <%= link_to 'Log out', destroy_user_session_path, method: "delete", data: { turbo_method: :delete } %>
    </div>
    <%= link_to 'Create Movie', new_movie_path %>
    <%= link_to 'Search OMDB', omdb_search_movies_path %>
    <%= link_to  'Show Movies', movies_path%>
<% else %>
    <%= link_to 'Sign in', new_user_session_path %>
<% end %>